export type DeviceType =
  | "Smoke Detector"
  | "Heat Detector"
  | "Pull Station"
  | "Horn/Strobe"
  | "Fire Alarm Panel"
  | "Annunciator"
  | "Emergency Light"
  | "Exit Sign"
  | "Fire Extinguisher"
  | "Sprinkler Flow Switch"
  | "Backflow Preventer";

export type DeviceStatus =
  | "not_tested"
  | "testing"
  | "passed"
  | "failed"
  | "deficiency"
  | "no_access";

export type DeviceCategory =
  | "Fire Alarm"
  | "Emergency Lighting"
  | "Sprinkler"
  | "Fire Extinguisher"
  | "Other";

export interface Device {
  id: string;
  label: string;
  type: DeviceType;
  category: DeviceCategory;
  floor: string;
  area: string;
  location: string;
  x: number; // percentage 0-100
  y: number; // percentage 0-100
  status: DeviceStatus;
  lastTestedAt?: string;
  deficiencyNote?: string;
}

export const FLOORS = ["P1 Parkade", "Main Floor", "2nd Floor", "Roof"];

export const MOCK_DEVICES: Device[] = [
  // P1 Parkade
  {
    id: "dev-p1-1",
    label: "PS-P1-01",
    type: "Pull Station",
    category: "Fire Alarm",
    floor: "P1 Parkade",
    area: "Exit A",
    location: "Northwest Stairwell Entrance",
    x: 15,
    y: 20,
    status: "not_tested",
  },
  {
    id: "dev-p1-2",
    label: "HD-P1-02",
    type: "Heat Detector",
    category: "Fire Alarm",
    floor: "P1 Parkade",
    area: "Parking Area",
    location: "Center Ceiling",
    x: 50,
    y: 40,
    status: "not_tested",
  },
  {
    id: "dev-p1-3",
    label: "FE-P1-03",
    type: "Fire Extinguisher",
    category: "Fire Extinguisher",
    floor: "P1 Parkade",
    area: "Elevator Lobby",
    location: "Wall Mount, Next to Elevators",
    x: 45,
    y: 70,
    status: "not_tested",
  },
  {
    id: "dev-p1-4",
    label: "HS-P1-04",
    type: "Horn/Strobe",
    category: "Fire Alarm",
    floor: "P1 Parkade",
    area: "Driveway",
    location: "South Wall",
    x: 80,
    y: 80,
    status: "not_tested",
  },
  {
    id: "dev-p1-5",
    label: "EL-P1-05",
    type: "Emergency Light",
    category: "Emergency Lighting",
    floor: "P1 Parkade",
    area: "Exit B",
    location: "Southeast Stairwell",
    x: 85,
    y: 25,
    status: "not_tested",
  },
  {
    id: "dev-p1-6",
    label: "FS-P1-06",
    type: "Sprinkler Flow Switch",
    category: "Sprinkler",
    floor: "P1 Parkade",
    area: "Sprinkler Room",
    location: "Main Riser",
    x: 20,
    y: 85,
    status: "not_tested",
  },
  {
    id: "dev-p1-7",
    label: "BF-P1-07",
    type: "Backflow Preventer",
    category: "Sprinkler",
    floor: "P1 Parkade",
    area: "Mechanical Room",
    location: "Water Entry",
    x: 25,
    y: 85,
    status: "not_tested",
  },
  {
    id: "dev-p1-8",
    label: "HD-P1-08",
    type: "Heat Detector",
    category: "Fire Alarm",
    floor: "P1 Parkade",
    area: "Storage Room",
    location: "Ceiling",
    x: 35,
    y: 15,
    status: "not_tested",
  },
  {
    id: "dev-p1-9",
    label: "EX-P1-09",
    type: "Exit Sign",
    category: "Emergency Lighting",
    floor: "P1 Parkade",
    area: "Exit A",
    location: "Above Door",
    x: 15,
    y: 18,
    status: "not_tested",
  },
  {
    id: "dev-p1-10",
    label: "EX-P1-10",
    type: "Exit Sign",
    category: "Emergency Lighting",
    floor: "P1 Parkade",
    area: "Exit B",
    location: "Above Door",
    x: 85,
    y: 23,
    status: "not_tested",
  },

  // Main Floor
  {
    id: "dev-m-1",
    label: "FACP-001",
    type: "Fire Alarm Panel",
    category: "Fire Alarm",
    floor: "Main Floor",
    area: "Electrical Room",
    location: "East Wall",
    x: 90,
    y: 50,
    status: "not_tested",
  },
  {
    id: "dev-m-2",
    label: "ANN-001",
    type: "Annunciator",
    category: "Fire Alarm",
    floor: "Main Floor",
    area: "Main Lobby",
    location: "Front Entrance",
    x: 50,
    y: 90,
    status: "not_tested",
  },
  {
    id: "dev-m-3",
    label: "SD-M-03",
    type: "Smoke Detector",
    category: "Fire Alarm",
    floor: "Main Floor",
    area: "Main Corridor",
    location: "Ceiling Center",
    x: 50,
    y: 60,
    status: "not_tested",
  },
  {
    id: "dev-m-4",
    label: "PS-M-04",
    type: "Pull Station",
    category: "Fire Alarm",
    floor: "Main Floor",
    area: "Main Lobby",
    location: "Next to Entrance",
    x: 45,
    y: 88,
    status: "not_tested",
  },
  {
    id: "dev-m-5",
    label: "HS-M-05",
    type: "Horn/Strobe",
    category: "Fire Alarm",
    floor: "Main Floor",
    area: "Main Corridor",
    location: "West Wall",
    x: 30,
    y: 60,
    status: "not_tested",
  },
  {
    id: "dev-m-6",
    label: "FE-M-06",
    type: "Fire Extinguisher",
    category: "Fire Extinguisher",
    floor: "Main Floor",
    area: "Kitchen",
    location: "Near Stove",
    x: 20,
    y: 30,
    status: "not_tested",
  },
  {
    id: "dev-m-7",
    label: "SD-M-07",
    type: "Smoke Detector",
    category: "Fire Alarm",
    floor: "Main Floor",
    area: "Office 101",
    location: "Ceiling",
    x: 70,
    y: 30,
    status: "not_tested",
  },
  {
    id: "dev-m-8",
    label: "EL-M-08",
    type: "Emergency Light",
    category: "Emergency Lighting",
    floor: "Main Floor",
    area: "Corridor North",
    location: "Ceiling",
    x: 50,
    y: 20,
    status: "not_tested",
  },
  {
    id: "dev-m-9",
    label: "EX-M-09",
    type: "Exit Sign",
    category: "Emergency Lighting",
    floor: "Main Floor",
    area: "Main Lobby",
    location: "Above Entrance",
    x: 50,
    y: 92,
    status: "not_tested",
  },
  {
    id: "dev-m-10",
    label: "SD-M-10",
    type: "Smoke Detector",
    category: "Fire Alarm",
    floor: "Main Floor",
    area: "Office 102",
    location: "Ceiling",
    x: 70,
    y: 50,
    status: "not_tested",
  },
  {
    id: "dev-m-11",
    label: "PS-M-11",
    type: "Pull Station",
    category: "Fire Alarm",
    floor: "Main Floor",
    area: "Rear Exit",
    location: "Next to Door",
    x: 50,
    y: 10,
    status: "not_tested",
  },

  // 2nd Floor
  {
    id: "dev-2-1",
    label: "SD-2-01",
    type: "Smoke Detector",
    category: "Fire Alarm",
    floor: "2nd Floor",
    area: "Corridor",
    location: "Center",
    x: 50,
    y: 50,
    status: "not_tested",
  },
  {
    id: "dev-2-2",
    label: "SD-2-02",
    type: "Smoke Detector",
    category: "Fire Alarm",
    floor: "2nd Floor",
    area: "Unit 201",
    location: "Living Room",
    x: 20,
    y: 30,
    status: "not_tested",
  },
  {
    id: "dev-2-3",
    label: "SD-2-03",
    type: "Smoke Detector",
    category: "Fire Alarm",
    floor: "2nd Floor",
    area: "Unit 202",
    location: "Living Room",
    x: 80,
    y: 30,
    status: "not_tested",
  },
  {
    id: "dev-2-4",
    label: "SD-2-04",
    type: "Smoke Detector",
    category: "Fire Alarm",
    floor: "2nd Floor",
    area: "Unit 203",
    location: "Living Room",
    x: 20,
    y: 70,
    status: "not_tested",
  },
  {
    id: "dev-2-5",
    label: "SD-2-05",
    type: "Smoke Detector",
    category: "Fire Alarm",
    floor: "2nd Floor",
    area: "Unit 204",
    location: "Living Room",
    x: 80,
    y: 70,
    status: "not_tested",
  },
  {
    id: "dev-2-6",
    label: "PS-2-06",
    type: "Pull Station",
    category: "Fire Alarm",
    floor: "2nd Floor",
    area: "Stairwell A",
    location: "Inside Door",
    x: 10,
    y: 50,
    status: "not_tested",
  },
  {
    id: "dev-2-7",
    label: "PS-2-07",
    type: "Pull Station",
    category: "Fire Alarm",
    floor: "2nd Floor",
    area: "Stairwell B",
    location: "Inside Door",
    x: 90,
    y: 50,
    status: "not_tested",
  },
  {
    id: "dev-2-8",
    label: "HS-2-08",
    type: "Horn/Strobe",
    category: "Fire Alarm",
    floor: "2nd Floor",
    area: "Corridor",
    location: "North End",
    x: 50,
    y: 20,
    status: "not_tested",
  },
  {
    id: "dev-2-9",
    label: "HS-2-09",
    type: "Horn/Strobe",
    category: "Fire Alarm",
    floor: "2nd Floor",
    area: "Corridor",
    location: "South End",
    x: 50,
    y: 80,
    status: "not_tested",
  },
  {
    id: "dev-2-10",
    label: "FE-2-10",
    type: "Fire Extinguisher",
    category: "Fire Extinguisher",
    floor: "2nd Floor",
    area: "Corridor",
    location: "Center Wall",
    x: 45,
    y: 50,
    status: "not_tested",
  },
  {
    id: "dev-2-11",
    label: "EL-2-11",
    type: "Emergency Light",
    category: "Emergency Lighting",
    floor: "2nd Floor",
    area: "Corridor",
    location: "Center",
    x: 55,
    y: 50,
    status: "not_tested",
  },

  // Roof
  {
    id: "dev-r-1",
    label: "HD-R-01",
    type: "Heat Detector",
    category: "Fire Alarm",
    floor: "Roof",
    area: "Elevator Machine Room",
    location: "Ceiling",
    x: 50,
    y: 50,
    status: "not_tested",
  },
  {
    id: "dev-r-2",
    label: "PS-R-02",
    type: "Pull Station",
    category: "Fire Alarm",
    floor: "Roof",
    area: "Roof Access",
    location: "Next to Door",
    x: 45,
    y: 55,
    status: "not_tested",
  },
  {
    id: "dev-r-3",
    label: "FE-R-03",
    type: "Fire Extinguisher",
    category: "Fire Extinguisher",
    floor: "Roof",
    area: "Elevator Machine Room",
    location: "Wall",
    x: 55,
    y: 45,
    status: "not_tested",
  },
  {
    id: "dev-r-4",
    label: "HS-R-04",
    type: "Horn/Strobe",
    category: "Fire Alarm",
    floor: "Roof",
    area: "Roof Deck",
    location: "Exterior Wall",
    x: 40,
    y: 60,
    status: "not_tested",
  },
  {
    id: "dev-r-5",
    label: "SD-R-05",
    type: "Smoke Detector",
    category: "Fire Alarm",
    floor: "Roof",
    area: "Stairwell C",
    location: "Ceiling",
    x: 80,
    y: 20,
    status: "not_tested",
  },
  {
    id: "dev-r-6",
    label: "EL-R-06",
    type: "Emergency Light",
    category: "Emergency Lighting",
    floor: "Roof",
    area: "Elevator Machine Room",
    location: "Wall",
    x: 52,
    y: 52,
    status: "not_tested",
  },
];
